[build]
  publish = "."
  command = "echo 'No build required - static files'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure assets in the public directory are accessible
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000"
